
[project_id]
value = "mvcqywuqkeerlmodohgw"

# Your Twilio Account SID
[TWILIO_ACCOUNT_SID]
value = "AC54b797ebe565b448f49220123b5fb5d0"

# Your Twilio Auth Token
[TWILIO_AUTH_TOKEN]
value = "4b75253f7f2847203c08fb5c8af48802"

# This will be filled in when you get your Twilio phone number
[TWILIO_PHONE_NUMBER]
value = ""
