// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvcqywuqkeerlmodohgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12Y3F5d3Vxa2Vlcmxtb2RvaGd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMzQwMTksImV4cCI6MjA1NjYxMDAxOX0.Ov6b3QX1Ze9KCMnpc5qKVFy36J23t1eB8KZDTg2lgfw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);